Repository ls1intum/Atlas, pull requests merged in 2025-02, with the labels that each got.

#41 `General`: Fix documentation and add markdown support
  docs/.readthedocs.yaml
  docs/admin/admin.md
  docs/admin/admin.rst
  docs/conf.py
  docs/dev/dev.md
  docs/dev/dev.rst
  docs/dev/setup/setup.md
  docs/dev/system-design/system-design.md
  docs/index.md
  docs/index.rst
  docs/requirements.txt
  docs/user/user.md
  docs/user/user.rst
Labels: documentation, ready for review

#44 `Development`: Add AtlasML to pull request title check
  .github/workflows/validate-pr-title.yml
Labels: github

#39 `AtlasML`: Add initial embedding model
  AtlasMl/atlasml/ml/VectorEmbeddings/FallbackModel.py
  AtlasMl/atlasml/ml/VectorEmbeddings/MainEmbeddingModel.py
  AtlasMl/atlasml/ml/VectorEmbeddings/__init__.py
  AtlasMl/atlasml/ml/__init__.py
  AtlasMl/atlasml/ml/ml_runner.py
  AtlasMl/atlasml/ml/model.py
  AtlasMl/atlasml/models/__init__.py
Labels: ready for review
